name: CI

on:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  toolchains:
    uses: ./.github/workflows/build-toolchains.yml
